// Template Registry — Central mapping of all 30 template IDs to metadata and components

import { TemplateMetadata, IndustryType } from "@/types/template";
import { CVData } from "@/types/cv";
import { ColorTheme, getColorTheme } from "./colors";
import React from "react";

// Import existing template components
import ModernTemplate from "@/components/templates/ModernTemplate";
import MinimalTemplate from "@/components/templates/MinimalTemplate";
import ProfessionalTemplate from "@/components/templates/ProfessionalTemplate";
import ExecutiveTemplate from "@/components/templates/ExecutiveTemplate";
import CreativeTemplate from "@/components/templates/CreativeTemplate";
import CorporateTemplate from "@/components/templates/CorporateTemplate";
import ATSFriendlyTemplate from "@/components/templates/ATSFriendlyTemplate";
import DeveloperTemplate from "@/components/templates/DeveloperTemplate";
import ElegantTemplate from "@/components/templates/ElegantTemplate";
import CompactTemplate from "@/components/templates/CompactTemplate";
import MarketingTemplate from "@/components/templates/MarketingTemplate";
import MedicalTemplate from "@/components/templates/MedicalTemplate";
import StudentTemplate from "@/components/templates/StudentTemplate";

export type TemplateComponent = React.ComponentType<{ data: CVData; colorTheme: ColorTheme }>;

// Map component getters with safe fallback
const componentMap: Record<string, TemplateComponent> = {
  modern: ModernTemplate,
  minimal: MinimalTemplate,
  professional: ProfessionalTemplate,
  executive: ExecutiveTemplate,
  creative: CreativeTemplate,
  corporate: CorporateTemplate,
  "ats-friendly": ATSFriendlyTemplate,
  developer: DeveloperTemplate,
  elegant: ElegantTemplate,
  compact: CompactTemplate,
  marketing: MarketingTemplate,
  medical: MedicalTemplate,
  student: StudentTemplate,
  teacher: ModernTemplate,
  sales: MarketingTemplate,
  business: ExecutiveTemplate,
  finance: CorporateTemplate,
  engineering: DeveloperTemplate,
  designer: CreativeTemplate,
  academic: ElegantTemplate,
  "two-column-modern": ProfessionalTemplate,
  timeline: ModernTemplate,
  infographic: CreativeTemplate,
  classic: MinimalTemplate,
  bold: MarketingTemplate,
  soft: ModernTemplate,
  dark: DeveloperTemplate,
  gradient: CreativeTemplate,
  card: MedicalTemplate,
  nordic: MinimalTemplate,
};

const allMetadata: TemplateMetadata[] = [
  {
    id: "modern",
    name: "Modern",
    description: "Clean, modern design with a bold colored header. Perfect for tech professionals and creatives.",
    category: "modern",
    style: "modern",
    industries: ["software-engineer", "designer", "general"],
    experienceLevels: ["mid", "senior"],
    atsScore: 85,
    isPremium: false,
    isFeatured: true,
    isNew: false,
    fonts: ["Segoe UI", "sans-serif"],
    sections: ["summary", "experience", "education", "skills", "projects", "certifications"],
    layout: "one-column",
    colorDefault: "blue",
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Elegant minimalist design with serif typography. Clean and understated for traditional industries.",
    category: "minimal",
    style: "minimal",
    industries: ["business", "legal", "general"],
    experienceLevels: ["entry", "mid", "senior"],
    atsScore: 90,
    isPremium: false,
    isFeatured: false,
    isNew: false,
    fonts: ["Georgia", "serif"],
    sections: ["summary", "experience", "education", "skills", "projects", "certifications"],
    layout: "one-column",
    colorDefault: "black",
  },
  {
    id: "professional",
    name: "Professional",
    description: "Two-column layout with a dark sidebar for contact and skills. Great for experienced professionals.",
    category: "professional",
    style: "two-column",
    industries: ["software-engineer", "business", "general"],
    experienceLevels: ["mid", "senior"],
    atsScore: 75,
    isPremium: false,
    isFeatured: true,
    isNew: false,
    fonts: ["Calibri", "sans-serif"],
    sections: ["summary", "experience", "education", "skills", "projects", "certifications"],
    layout: "sidebar-left",
    colorDefault: "navy",
  },
  {
    id: "executive",
    name: "Executive",
    description: "Refined executive design with serif headings and gold accents. Ideal for senior leadership roles.",
    category: "executive",
    style: "elegant",
    industries: ["business", "legal", "general"],
    experienceLevels: ["senior"],
    atsScore: 80,
    isPremium: false,
    isFeatured: true,
    isNew: true,
    fonts: ["Georgia", "serif"],
    sections: ["summary", "experience", "education", "skills", "projects", "certifications"],
    layout: "two-column",
    colorDefault: "navy",
  },
  {
    id: "creative",
    name: "Creative",
    description: "Bold, asymmetric design with color blocks. Perfect for designers, marketers, and creative directors.",
    category: "creative",
    style: "creative",
    industries: ["designer", "marketing", "general"],
    experienceLevels: ["entry", "mid"],
    atsScore: 65,
    isPremium: false,
    isFeatured: true,
    isNew: true,
    fonts: ["Segoe UI", "sans-serif"],
    sections: ["summary", "experience", "education", "skills", "projects", "certifications"],
    layout: "sidebar-left",
    colorDefault: "purple",
  },
  {
    id: "corporate",
    name: "Corporate",
    description: "Classic corporate single-column design with conservative typography for business & management.",
    category: "corporate",
    style: "corporate",
    industries: ["business", "accounting", "hr", "legal"],
    experienceLevels: ["mid", "senior"],
    atsScore: 88,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Arial", "sans-serif"],
    sections: ["summary", "experience", "education", "skills", "projects", "certifications"],
    layout: "one-column",
    colorDefault: "navy",
  },
  {
    id: "ats-friendly",
    name: "ATS Friendly",
    description: "Maximum ATS compatibility (98% score). Simple text formatting for automated applicant tracking systems.",
    category: "ats",
    style: "ats-friendly",
    industries: ["software-engineer", "business", "general"],
    experienceLevels: ["entry", "mid", "senior"],
    atsScore: 98,
    isPremium: false,
    isFeatured: true,
    isNew: true,
    fonts: ["Arial", "sans-serif"],
    sections: ["summary", "experience", "education", "skills", "projects", "certifications"],
    layout: "one-column",
    colorDefault: "black",
  },
  {
    id: "developer",
    name: "Developer",
    description: "Tech-inspired design with monospace accents and terminal aesthetic. Highlights code projects prominently.",
    category: "developer",
    style: "two-column",
    industries: ["software-engineer", "engineering"],
    experienceLevels: ["entry", "mid", "senior"],
    atsScore: 72,
    isPremium: false,
    isFeatured: true,
    isNew: true,
    fonts: ["Fira Code", "monospace"],
    sections: ["summary", "experience", "education", "skills", "projects", "certifications"],
    layout: "sidebar-left",
    colorDefault: "green",
  },
  {
    id: "elegant",
    name: "Elegant",
    description: "Refined serif design with ornate section dividers and generous whitespace.",
    category: "elegant",
    style: "elegant",
    industries: ["designer", "business", "legal", "general"],
    experienceLevels: ["mid", "senior"],
    atsScore: 78,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Playfair Display", "serif"],
    sections: ["summary", "experience", "education", "skills", "projects", "certifications"],
    layout: "one-column",
    colorDefault: "black",
  },
  {
    id: "compact",
    name: "Compact",
    description: "Dense two-column layout optimized for maximum content density and small margins.",
    category: "simple",
    style: "two-column",
    industries: ["software-engineer", "engineering", "general"],
    experienceLevels: ["mid", "senior"],
    atsScore: 70,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Arial", "sans-serif"],
    sections: ["summary", "experience", "education", "skills", "projects", "certifications"],
    layout: "two-column",
    colorDefault: "blue",
  },
  {
    id: "marketing",
    name: "Marketing & Growth",
    description: "Infographic-style layout with metrics badges and campaign highlights.",
    category: "marketing",
    style: "creative",
    industries: ["marketing", "sales"],
    experienceLevels: ["entry", "mid", "senior"],
    atsScore: 80,
    isPremium: false,
    isFeatured: true,
    isNew: true,
    fonts: ["Inter", "sans-serif"],
    sections: ["summary", "experience", "education", "skills", "projects", "certifications"],
    layout: "one-column",
    colorDefault: "teal",
  },
  {
    id: "medical",
    name: "Medical & Clinical",
    description: "Clean clinical aesthetic with medical license callouts and hospital experience timeline.",
    category: "medical",
    style: "professional",
    industries: ["medical"],
    experienceLevels: ["entry", "mid", "senior"],
    atsScore: 92,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["System-UI", "sans-serif"],
    sections: ["summary", "experience", "education", "skills", "certifications"],
    layout: "two-column",
    colorDefault: "blue",
  },
  {
    id: "student",
    name: "Student & Graduate",
    description: "Education and academic projects first, perfect for students and early-career job seekers.",
    category: "student",
    style: "minimal",
    industries: ["student", "general"],
    experienceLevels: ["entry"],
    atsScore: 88,
    isPremium: false,
    isFeatured: true,
    isNew: true,
    fonts: ["Inter", "sans-serif"],
    sections: ["summary", "education", "projects", "experience", "skills"],
    layout: "one-column",
    colorDefault: "blue",
  },
  {
    id: "teacher",
    name: "Teacher & Educator",
    description: "Warm academic layout placing teaching experience and certifications in clear focus.",
    category: "teacher",
    style: "academic",
    industries: ["teacher"],
    experienceLevels: ["mid", "senior"],
    atsScore: 85,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Georgia", "serif"],
    sections: ["summary", "experience", "education", "skills", "certifications"],
    layout: "one-column",
    colorDefault: "teal",
  },
  {
    id: "sales",
    name: "Sales & Revenue",
    description: "Achievement-focused layout with performance metrics and quota highlights.",
    category: "sales",
    style: "modern",
    industries: ["sales", "business"],
    experienceLevels: ["mid", "senior"],
    atsScore: 82,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Inter", "sans-serif"],
    sections: ["summary", "experience", "education", "skills", "certifications"],
    layout: "one-column",
    colorDefault: "red",
  },
  {
    id: "business",
    name: "Business Analyst",
    description: "Structured corporate layout for business analysts and consultants.",
    category: "business",
    style: "corporate",
    industries: ["business", "accounting", "hr"],
    experienceLevels: ["mid", "senior"],
    atsScore: 86,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Calibri", "sans-serif"],
    sections: ["summary", "experience", "education", "skills", "projects"],
    layout: "two-column",
    colorDefault: "navy",
  },
  {
    id: "finance",
    name: "Finance & Banking",
    description: "Data-dense financial layout with quantitative emphasis and formal rules.",
    category: "finance",
    style: "corporate",
    industries: ["accounting", "business"],
    experienceLevels: ["mid", "senior"],
    atsScore: 90,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Georgia", "serif"],
    sections: ["summary", "experience", "education", "skills", "certifications"],
    layout: "one-column",
    colorDefault: "black",
  },
  {
    id: "engineering",
    name: "Technical Engineer",
    description: "Technical architecture layout emphasizing technical skills and project metrics.",
    category: "engineering",
    style: "two-column",
    industries: ["engineering", "software-engineer"],
    experienceLevels: ["mid", "senior"],
    atsScore: 84,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Fira Code", "monospace"],
    sections: ["summary", "experience", "skills", "projects", "education"],
    layout: "sidebar-left",
    colorDefault: "green",
  },
  {
    id: "designer",
    name: "UI/UX Designer",
    description: "Visual portfolio layout with large typography and project link highlights.",
    category: "designer",
    style: "creative",
    industries: ["designer", "marketing"],
    experienceLevels: ["entry", "mid", "senior"],
    atsScore: 68,
    isPremium: false,
    isFeatured: true,
    isNew: true,
    fonts: ["Segoe UI", "sans-serif"],
    sections: ["summary", "projects", "experience", "skills", "education"],
    layout: "sidebar-left",
    colorDefault: "purple",
  },
  {
    id: "academic",
    name: "Academic CV",
    description: "Formal academic layout designed for research, publications, and grant history.",
    category: "academic",
    style: "academic",
    industries: ["teacher", "general"],
    experienceLevels: ["senior"],
    atsScore: 85,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Georgia", "serif"],
    sections: ["summary", "education", "experience", "certifications", "projects"],
    layout: "one-column",
    colorDefault: "gray",
  },
  {
    id: "two-column-modern",
    name: "Two-Column Modern",
    description: "Balanced 50/50 split layout with distinct visual contrast between sections.",
    category: "modern",
    style: "two-column",
    industries: ["general"],
    experienceLevels: ["entry", "mid", "senior"],
    atsScore: 78,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Segoe UI", "sans-serif"],
    sections: ["summary", "experience", "education", "skills"],
    layout: "two-column",
    colorDefault: "blue",
  },
  {
    id: "timeline",
    name: "Career Timeline",
    description: "Connected vertical timeline highlighting key career milestones.",
    category: "creative",
    style: "creative",
    industries: ["general"],
    experienceLevels: ["mid", "senior"],
    atsScore: 72,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Inter", "sans-serif"],
    sections: ["summary", "experience", "education", "skills"],
    layout: "one-column",
    colorDefault: "teal",
  },
  {
    id: "infographic",
    name: "Infographic Pro",
    description: "Visual elements and skill bars for a standout creative presentation.",
    category: "creative",
    style: "creative",
    industries: ["designer", "marketing"],
    experienceLevels: ["entry", "mid"],
    atsScore: 66,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Inter", "sans-serif"],
    sections: ["summary", "experience", "skills", "projects"],
    layout: "sidebar-left",
    colorDefault: "purple",
  },
  {
    id: "classic",
    name: "Classic Harvard",
    description: "Traditional Harvard-standard resume structure with centered headings.",
    category: "minimal",
    style: "minimal",
    industries: ["business", "legal", "general"],
    experienceLevels: ["entry", "mid", "senior"],
    atsScore: 95,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Georgia", "serif"],
    sections: ["summary", "education", "experience", "skills"],
    layout: "one-column",
    colorDefault: "black",
  },
  {
    id: "bold",
    name: "Bold Impact",
    description: "High-contrast headings and large typography for high-impact roles.",
    category: "modern",
    style: "modern",
    industries: ["marketing", "sales"],
    experienceLevels: ["mid", "senior"],
    atsScore: 82,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Inter", "sans-serif"],
    sections: ["summary", "experience", "skills", "education"],
    layout: "one-column",
    colorDefault: "red",
  },
  {
    id: "soft",
    name: "Soft & Warm",
    description: "Gentle rounded cards and warm neutral tones for a friendly aesthetic.",
    category: "modern",
    style: "modern",
    industries: ["general"],
    experienceLevels: ["entry", "mid"],
    atsScore: 84,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Segoe UI", "sans-serif"],
    sections: ["summary", "experience", "education", "skills"],
    layout: "one-column",
    colorDefault: "gray",
  },
  {
    id: "dark",
    name: "Sleek Dark",
    description: "Dark-themed resume layout with crisp light text and vibrant accents.",
    category: "creative",
    style: "creative",
    industries: ["software-engineer", "designer"],
    experienceLevels: ["entry", "mid", "senior"],
    atsScore: 70,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Fira Code", "monospace"],
    sections: ["summary", "experience", "projects", "skills"],
    layout: "sidebar-left",
    colorDefault: "black",
  },
  {
    id: "gradient",
    name: "Gradient Tech",
    description: "Modern startup aesthetic with subtle gradient header accents.",
    category: "modern",
    style: "modern",
    industries: ["software-engineer", "marketing"],
    experienceLevels: ["entry", "mid"],
    atsScore: 80,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Inter", "sans-serif"],
    sections: ["summary", "experience", "projects", "skills"],
    layout: "one-column",
    colorDefault: "blue",
  },
  {
    id: "card",
    name: "Modular Cards",
    description: "Clean modular card layout separating every resume section.",
    category: "modern",
    style: "modern",
    industries: ["general"],
    experienceLevels: ["entry", "mid"],
    atsScore: 76,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Segoe UI", "sans-serif"],
    sections: ["summary", "experience", "education", "skills"],
    layout: "two-column",
    colorDefault: "blue",
  },
  {
    id: "nordic",
    name: "Nordic Minimal",
    description: "Scandinavian minimalist layout with ultra-clean lines and wide margins.",
    category: "minimal",
    style: "minimal",
    industries: ["designer", "business", "general"],
    experienceLevels: ["entry", "mid", "senior"],
    atsScore: 92,
    isPremium: false,
    isFeatured: false,
    isNew: true,
    fonts: ["Segoe UI", "sans-serif"],
    sections: ["summary", "experience", "education", "skills"],
    layout: "one-column",
    colorDefault: "gray",
  },
];

// Registry mapping
const templateRegistry: Record<string, { metadata: TemplateMetadata; component: TemplateComponent }> = {};

allMetadata.forEach((meta) => {
  templateRegistry[meta.id] = {
    metadata: meta,
    component: componentMap[meta.id] || ModernTemplate,
  };
});

// ---- Public API ----

export function getTemplateById(id: string) {
  return templateRegistry[id];
}

export function getTemplateComponent(id: string): TemplateComponent {
  return templateRegistry[id]?.component || ModernTemplate;
}

export function getTemplateMetadata(id: string): TemplateMetadata | undefined {
  return templateRegistry[id]?.metadata;
}

export function getAllTemplates(): TemplateMetadata[] {
  return allMetadata;
}

export function getTemplatesByCategory(category: string): TemplateMetadata[] {
  return getAllTemplates().filter((t) => t.category === category);
}

export function getTemplatesByStyle(style: string): TemplateMetadata[] {
  return getAllTemplates().filter((t) => t.style === style);
}

export function getTemplatesByIndustry(industry: string): TemplateMetadata[] {
  return getAllTemplates().filter((t) => t.industries.includes(industry as IndustryType));
}

export function getFeaturedTemplates(): TemplateMetadata[] {
  return getAllTemplates().filter((t) => t.isFeatured);
}

export function searchTemplates(query: string): TemplateMetadata[] {
  const lower = query.toLowerCase();
  return getAllTemplates().filter(
    (t) =>
      t.name.toLowerCase().includes(lower) ||
      t.description.toLowerCase().includes(lower) ||
      t.category.toLowerCase().includes(lower) ||
      t.style.toLowerCase().includes(lower) ||
      t.industries.some((i) => i.toLowerCase().includes(lower))
  );
}

export function getDefaultColorTheme(templateId: string): string {
  return templateRegistry[templateId]?.metadata.colorDefault || "blue";
}

export { getColorTheme };
